export const articles = [
    { id: 1, 
      tags: ["#АНИМАЦИЯ", "#ДИЗАЙН"], 
      title: 'Название статьи №1 lorem ipsum dolor sit amet.', 
      text1: 'Lorem ipsum dolor sit amet consectetur. Nibh feugiat hendrerit fusce felis. Massa cras tempor nibh nunc maecenas aliquam nisl diam. In eu tempus at enim ac nullam ut. Nunc amet elementum neque in.Ultrices sit a ornare scelerisque aliquet. Nullam orci in vel aliquam lectus turpis. Vel eu mollis etiam arcu elit adipiscing vel pellentesque. Venenatis est duis malesuada egestas sit. Sed integer lacinia posuere in rhoncus sed mauris nisl. Nunc mi pellentesque mi scelerisque. Vitae non ultrices sit pulvinar aliquam eu adipiscing risus aenean. Sodales cursus mi sit integer neque. Pharetra tristique sed sapien hac sit nunc augue augue sagittis. Dignissim nisl enim arcu pulvinar vivamus. Nunc elit nunc tempus at in nec sit egestas. Velit enim sed urna velit augue malesuada elementum volutpat condimentum. Duis aenean tristique volutpat risus elementum sagittis augue orci erat. Viverra in purus semper pellentesque tortor ullamcorper quis at.',
      text2: 'Ullamcorper eu scelerisque purus eget egestas malesuada. Amet maecenas rutrum at libero pulvinar arcu lorem. Iaculis ac dictum vulputate eu id ligula tellus libero. Gravida ultrices in ut pretium molestie euismod a. Nibh non arcu habitant id. Consectetur elementum habitasse non venenatis nullam augue. Dictum scelerisque sed donec tortor tincidunt maecenas scelerisque vel. Commodo felis nunc quam et massa. Felis aenean ullamcorper mattis et fermentum lorem malesuada. Consequat id gravida aliquam tempor ultrices velit tincidunt. Quam sed urna ultricies vulputate et nibh in turpis. Amet scelerisque suspendisse condimentum justo urna scelerisque. Lacus euismod hac non turpis sagittis sapien. Hendrerit risus venenatis est ut netus dui. Mauris nulla pellentesque faucibus amet in magna.',
      text3: 'Nisl quisque maecenas consectetur venenatis proin enim amet pharetra. Tortor lacus nunc sed at porttitor sapien. Lorem eget morbi integer phasellus lectus. Platea curabitur sed morbi volutpat. Vestibulum enim aliquet at auctor sapien elementum enim sed. Varius commodo diam aliquet enim senectus eu morbi.',
      date:"20_03_2023",
      image:require("../assets/images/article1.png")
    },
    { id: 2, 
      tags: ["#АНИМАЦИЯ", "#ДИЗАЙН"], 
      title: 'Название статьи №2 lorem ipsum dolor sit amet.', 
      text1: 'Lorem ipsum dolor sit amet consectetur. Nibh feugiat hendrerit fusce felis. Massa cras tempor nibh nunc maecenas aliquam nisl diam. In eu tempus at enim ac nullam ut. Nunc amet elementum neque in.Ultrices sit a ornare scelerisque aliquet. Nullam orci in vel aliquam lectus turpis. Vel eu mollis etiam arcu elit adipiscing vel pellentesque. Venenatis est duis malesuada egestas sit. Sed integer lacinia posuere in rhoncus sed mauris nisl. Nunc mi pellentesque mi scelerisque. Vitae non ultrices sit pulvinar aliquam eu adipiscing risus aenean. Sodales cursus mi sit integer neque. Pharetra tristique sed sapien hac sit nunc augue augue sagittis. Dignissim nisl enim arcu pulvinar vivamus. Nunc elit nunc tempus at in nec sit egestas. Velit enim sed urna velit augue malesuada elementum volutpat condimentum. Duis aenean tristique volutpat risus elementum sagittis augue orci erat. Viverra in purus semper pellentesque tortor ullamcorper quis at.',
      text2: 'Ullamcorper eu scelerisque purus eget egestas malesuada. Amet maecenas rutrum at libero pulvinar arcu lorem. Iaculis ac dictum vulputate eu id ligula tellus libero. Gravida ultrices in ut pretium molestie euismod a. Nibh non arcu habitant id. Consectetur elementum habitasse non venenatis nullam augue. Dictum scelerisque sed donec tortor tincidunt maecenas scelerisque vel. Commodo felis nunc quam et massa. Felis aenean ullamcorper mattis et fermentum lorem malesuada. Consequat id gravida aliquam tempor ultrices velit tincidunt. Quam sed urna ultricies vulputate et nibh in turpis. Amet scelerisque suspendisse condimentum justo urna scelerisque. Lacus euismod hac non turpis sagittis sapien. Hendrerit risus venenatis est ut netus dui. Mauris nulla pellentesque faucibus amet in magna.',
      text3: 'Nisl quisque maecenas consectetur venenatis proin enim amet pharetra. Tortor lacus nunc sed at porttitor sapien. Lorem eget morbi integer phasellus lectus. Platea curabitur sed morbi volutpat. Vestibulum enim aliquet at auctor sapien elementum enim sed. Varius commodo diam aliquet enim senectus eu morbi.',
      date:"20_03_2023",
      image:require("../assets/images/article1.png")
    },
    { id: 3, 
      tags: ["#АНИМАЦИЯ", "#ДИЗАЙН"], 
      title: 'Название статьи №3 lorem ipsum dolor sit amet.', 
      text1: 'Lorem ipsum dolor sit amet consectetur. Nibh feugiat hendrerit fusce felis. Massa cras tempor nibh nunc maecenas aliquam nisl diam. In eu tempus at enim ac nullam ut. Nunc amet elementum neque in.Ultrices sit a ornare scelerisque aliquet. Nullam orci in vel aliquam lectus turpis. Vel eu mollis etiam arcu elit adipiscing vel pellentesque. Venenatis est duis malesuada egestas sit. Sed integer lacinia posuere in rhoncus sed mauris nisl. Nunc mi pellentesque mi scelerisque. Vitae non ultrices sit pulvinar aliquam eu adipiscing risus aenean. Sodales cursus mi sit integer neque. Pharetra tristique sed sapien hac sit nunc augue augue sagittis. Dignissim nisl enim arcu pulvinar vivamus. Nunc elit nunc tempus at in nec sit egestas. Velit enim sed urna velit augue malesuada elementum volutpat condimentum. Duis aenean tristique volutpat risus elementum sagittis augue orci erat. Viverra in purus semper pellentesque tortor ullamcorper quis at.',
      text2: 'Ullamcorper eu scelerisque purus eget egestas malesuada. Amet maecenas rutrum at libero pulvinar arcu lorem. Iaculis ac dictum vulputate eu id ligula tellus libero. Gravida ultrices in ut pretium molestie euismod a. Nibh non arcu habitant id. Consectetur elementum habitasse non venenatis nullam augue. Dictum scelerisque sed donec tortor tincidunt maecenas scelerisque vel. Commodo felis nunc quam et massa. Felis aenean ullamcorper mattis et fermentum lorem malesuada. Consequat id gravida aliquam tempor ultrices velit tincidunt. Quam sed urna ultricies vulputate et nibh in turpis. Amet scelerisque suspendisse condimentum justo urna scelerisque. Lacus euismod hac non turpis sagittis sapien. Hendrerit risus venenatis est ut netus dui. Mauris nulla pellentesque faucibus amet in magna.',
      text3: 'Nisl quisque maecenas consectetur venenatis proin enim amet pharetra. Tortor lacus nunc sed at porttitor sapien. Lorem eget morbi integer phasellus lectus. Platea curabitur sed morbi volutpat. Vestibulum enim aliquet at auctor sapien elementum enim sed. Varius commodo diam aliquet enim senectus eu morbi.',
      date:"20_03_2023",
      image:require("../assets/images/article1.png")
    },
  ];